# Generated by Django 5.0 on 2024-01-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardgroup',
            name='status',
        ),
    ]
