# Generated by Django 4.2.7 on 2023-12-02 21:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0002_flashcardgroup_author_flashcard'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flashcard',
            managers=[
                ('flashcardManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='flashcardgroup',
            managers=[
                ('groupManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='language',
            field=models.CharField(default='', max_length=250),
        ),
    ]
