# Generated by Django 4.2.7 on 2023-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0003_alter_flashcard_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardgroup',
            name='cardQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
