# Generated by Django 4.2.7 on 2023-12-21 20:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcardApp', '0005_alter_flashcardgroup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardgroup',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardgroup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 38, 34, 486842)),
        ),
    ]
