# Generated by Django 4.2.7 on 2023-12-21 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0009_alter_flashcardgroup_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardgroup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 21, 49, 19, 640171)),
        ),
    ]
